-- MySQL Script generated by MySQL Workbench
-- Sun Apr 29 21:17:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema treption
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema treption
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `treption` DEFAULT CHARACTER SET utf8 ;
USE `treption` ;

-- -----------------------------------------------------
-- Table `treption`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`document` ;

CREATE TABLE IF NOT EXISTS `treption`.`document` (
  `document_id` INT NOT NULL AUTO_INCREMENT,
  `sentence_count` INT NULL,
  `datetime` DATETIME NULL,
  `value` LONGTEXT NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`document_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`sentence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`sentence` ;

CREATE TABLE IF NOT EXISTS `treption`.`sentence` (
  `sentence_id` INT NOT NULL AUTO_INCREMENT,
  `document_id` INT NOT NULL,
  `word_count` INT NULL,
  `document_position` INT NULL,
  `value` LONGTEXT NULL,
  PRIMARY KEY (`sentence_id`, `document_id`),
  INDEX `fk_sentence_document_idx` (`document_id` ASC),
  CONSTRAINT `fk_sentence_document`
    FOREIGN KEY (`document_id`)
    REFERENCES `treption`.`document` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`sentence_word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`sentence_word` ;

CREATE TABLE IF NOT EXISTS `treption`.`sentence_word` (
  `word_id` INT NOT NULL AUTO_INCREMENT,
  `sentence_id` INT NOT NULL,
  `word_position` INT NULL,
  `value` VARCHAR(255) NULL,
  `pos` VARCHAR(45) NULL,
  PRIMARY KEY (`word_id`, `sentence_id`),
  INDEX `fk_word_sentence1_idx` (`sentence_id` ASC),
  CONSTRAINT `fk_word_sentence1`
    FOREIGN KEY (`sentence_id`)
    REFERENCES `treption`.`sentence` (`sentence_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`user` ;

CREATE TABLE IF NOT EXISTS `treption`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`predicate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`predicate` ;

CREATE TABLE IF NOT EXISTS `treption`.`predicate` (
  `predicate_id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`predicate_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`triple`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`triple` ;

CREATE TABLE IF NOT EXISTS `treption`.`triple` (
  `triple_id` INT NOT NULL AUTO_INCREMENT,
  `subject_id` INT NOT NULL,
  `object_id` INT NOT NULL,
  `predicate_id` INT NOT NULL,
  PRIMARY KEY (`triple_id`, `subject_id`, `object_id`, `predicate_id`),
  INDEX `fk_triple_sentence_word1_idx` (`subject_id` ASC),
  INDEX `fk_triple_sentence_word2_idx` (`object_id` ASC),
  INDEX `fk_triple_predicate1_idx` (`predicate_id` ASC),
  CONSTRAINT `fk_triple_sentence_word1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `treption`.`sentence_word` (`word_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triple_sentence_word2`
    FOREIGN KEY (`object_id`)
    REFERENCES `treption`.`sentence_word` (`word_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triple_predicate1`
    FOREIGN KEY (`predicate_id`)
    REFERENCES `treption`.`predicate` (`predicate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`action` ;

CREATE TABLE IF NOT EXISTS `treption`.`action` (
  `action_id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NULL,
  `triple_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`action_id`, `triple_id`, `user_id`),
  INDEX `fk_action_triple1_idx` (`triple_id` ASC),
  INDEX `fk_action_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_action_triple1`
    FOREIGN KEY (`triple_id`)
    REFERENCES `treption`.`triple` (`triple_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_action_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `treption`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
