-- MySQL Script generated by MySQL Workbench
-- Mon May 21 14:10:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema treption
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema treption
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `treption` DEFAULT CHARACTER SET utf8 ;
USE `treption` ;

-- -----------------------------------------------------
-- Table `treption`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`user` ;

CREATE TABLE IF NOT EXISTS `treption`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`document` ;

CREATE TABLE IF NOT EXISTS `treption`.`document` (
  `document_id` INT NOT NULL AUTO_INCREMENT,
  `sentence_count` INT NULL,
  `datetime` DATETIME NULL,
  `value` LONGTEXT NULL,
  `color` VARCHAR(45) NULL,
  `owner_id` INT NOT NULL,
  `graph_id` VARCHAR(45) NULL,
  PRIMARY KEY (`document_id`, `owner_id`),
  INDEX `fk_document_user1_idx` (`owner_id` ASC),
  CONSTRAINT `fk_document_user1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `treption`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`sentence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`sentence` ;

CREATE TABLE IF NOT EXISTS `treption`.`sentence` (
  `sentence_id` INT NOT NULL AUTO_INCREMENT,
  `document_id` INT NOT NULL,
  `word_count` INT NULL,
  `document_position` INT NULL,
  `value` LONGTEXT NULL,
  PRIMARY KEY (`sentence_id`, `document_id`),
  INDEX `fk_sentence_document_idx` (`document_id` ASC),
  CONSTRAINT `fk_sentence_document`
    FOREIGN KEY (`document_id`)
    REFERENCES `treption`.`document` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`sentence_word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`sentence_word` ;

CREATE TABLE IF NOT EXISTS `treption`.`sentence_word` (
  `word_id` INT NOT NULL AUTO_INCREMENT,
  `sentence_id` INT NOT NULL,
  `word_position` INT NULL,
  `value` VARCHAR(255) NULL,
  `pos` VARCHAR(45) NULL,
  PRIMARY KEY (`word_id`, `sentence_id`),
  INDEX `fk_word_sentence1_idx` (`sentence_id` ASC),
  CONSTRAINT `fk_word_sentence1`
    FOREIGN KEY (`sentence_id`)
    REFERENCES `treption`.`sentence` (`sentence_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`action` ;

CREATE TABLE IF NOT EXISTS `treption`.`action` (
  `action_id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NULL,
  `user_id` INT NOT NULL,
  `action_key` VARCHAR(45) NULL,
  `action_value` INT NULL,
  PRIMARY KEY (`action_id`, `user_id`),
  INDEX `fk_action_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_action_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `treption`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`triple`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`triple` ;

CREATE TABLE IF NOT EXISTS `treption`.`triple` (
  `triple_id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(100) NULL,
  `predicate` VARCHAR(100) NULL,
  `object` VARCHAR(100) NULL,
  `sentence_id` INT NOT NULL,
  PRIMARY KEY (`triple_id`, `sentence_id`),
  INDEX `fk_triple_sentence1_idx` (`sentence_id` ASC),
  CONSTRAINT `fk_triple_sentence1`
    FOREIGN KEY (`sentence_id`)
    REFERENCES `treption`.`sentence` (`sentence_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`vote` ;

CREATE TABLE IF NOT EXISTS `treption`.`vote` (
  `votes_id` INT NOT NULL AUTO_INCREMENT,
  `agree` TINYINT NULL,
  `user_id` INT NOT NULL,
  `timestamp` TIMESTAMP NULL,
  `triple_id` INT NOT NULL,
  `points` INT NULL,
  `action_key` VARCHAR(45) NULL,
  `tournament_id` INT NULL,
  PRIMARY KEY (`votes_id`, `user_id`, `triple_id`),
  INDEX `fk_votes_user1_idx` (`user_id` ASC),
  INDEX `fk_vote_triple1_idx` (`triple_id` ASC),
  CONSTRAINT `fk_votes_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `treption`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_triple1`
    FOREIGN KEY (`triple_id`)
    REFERENCES `treption`.`triple` (`triple_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `treption`.`tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `treption`.`tournament` ;

CREATE TABLE IF NOT EXISTS `treption`.`tournament` (
  `tournament_id` INT NOT NULL AUTO_INCREMENT,
  `challenger_id` INT NOT NULL,
  `competitor_id` INT NOT NULL,
  `start_time` DATETIME NULL,
  `duration` INT NULL,
  `challenger_points` INT NULL,
  `competitor_points` INT NULL,
  PRIMARY KEY (`tournament_id`, `challenger_id`, `competitor_id`),
  INDEX `fk_tournament_user1_idx` (`challenger_id` ASC),
  INDEX `fk_tournament_user2_idx` (`competitor_id` ASC),
  CONSTRAINT `fk_tournament_user1`
    FOREIGN KEY (`challenger_id`)
    REFERENCES `treption`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tournament_user2`
    FOREIGN KEY (`competitor_id`)
    REFERENCES `treption`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
