version: '3'
services: 
  web: 
    build: 
      context: ./app/client/ 
      dockerfile: Dockerfile.web
    ports: 
      - "8080:8080"
    volumes: 
      - ./app/client:/var/www/treption
  api: 
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: treption
    ports: 
      - "5000:5000"
    volumes: 
      - ../treption:/opt/code
  db:  
    image: mysql:latest
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
  postagger: 
    image: motiz88/corenlp
    ports: 
      - 9000:9000
  