version: '3'
services: 
  web: 
    build: 
      context: ./app/client/ 
      dockerfile: Dockerfile.web
    ports: 
      - "3000:3000"
    volumes: 
      - ./app/client:/var/www/treption
  api: 
    build: 
      context: ./app/server/
      dockerfile: Dockerfile.api
    container_name: treption
    ports: 
      - "5000:5000"
    volumes: 
      - ../treption:/opt/code
  db:  
    build:
      context: ./app/db/
      dockerfile: Dockerfile.mysql
    ports: 
      - 3306:3306
    volumes: 
      - ./app/db:/root
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
  postagger: 
    image: motiz88/corenlp
    ports: 
      - 9000:9000
  