FROM node:9.6.1

WORKDIR /var/www/treption/app/client

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install 
RUN npm install react-scripts@1.1.1 -g

CMD ["npm", "start"]

# RUN ln -s /var/www/treption/treption.nginx.conf /etc/nginx/conf.d/

