export const SET_DOCUMENTS = 'SET_DOCUMENTS'
export const SET_DOCUMENT = 'SET_DOCUMENT'
export const SET_SENTENCE = 'SET_SENTENCE'
export const SET_PREDICATES = 'SET_PREDICATES'
export const SET_TRIPLES = 'SET_TRIPLES'
export const REPLACE_TRIPLE = 'REPLACE_TRIPLE'

export const ADD_PREDICATE = 'ADD_PREDICATE'

export const EXTRACT_WORD = 'EXTRACT_WORD'
export const EXTRACT_PREDICATE = 'EXTRACT_PREDICATE'
export const SET_EXTRACTING_STAGE = 'SET_EXTRACTING_STAGE'

export const SET_TRIPLE_SUBJECT = 'SET_TRIPLE_SUBJECT'
export const SET_TRIPLE_PREDICATE = 'SET_TRIPLE_PREDICATE'
export const SET_TRIPLE_OBJECT = 'SET_TRIPLE_OBJECT'
export const SET_SAVED_TRIPLE = 'SET_SAVED_TRIPLE'

export const SET_USER = 'SET_USER'
export const SET_LAST_EDITED_DOCUMENT_ID = 'SET_LAST_EDITED_DOCUMENT_ID'
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'

export const SET_PLAYER = 'SET_PLAYER'

export const DOCUMENT_LOADING_STATE = 'DOCUMENT_LOADING_STATE'
export const SENTENCE_LOADING_STATE = 'SENTENCE_LOADING_STATE'

export const SELECTED_TRIPLE_ATTRIBUTE = 'SELECTED_TRIPLE_ATTRIBUTE'
export const REMOVE_FROM_TRIPLE = 'REMOVE_FROM_TRIPLE'

export const AUTO_SUBJECT_MOVEMENT = 'SET_AUTO_SUBJECT_MOVEMENT'
export const AUTO_OBJECT_MOVEMENT = 'SET_AUTO_OBJECT_MOVEMENT'

export const EXTRACTION_FEEDBACK_BOX = 'EXTRACTION_FEEDBACK_BOX'
export const REMOVE_CONCEPT = 'REMOVE_CONCEPT'