export const SET_DOCUMENTS = 'SET_DOCUMENTS'
export const SET_DOCUMENT = 'SET_DOCUMENT'
export const SET_SENTENCE = 'SET_SENTENCE'
export const SET_PREDICATES = 'SET_PREDICATES'

export const ADD_PREDICATE = 'ADD_PREDICATE'

export const EXTRACT_WORD = 'EXTRACT_WORD'
export const EXTRACT_PREDICATE = 'EXTRACT_PREDICATE'